parameters:
#    vision_presentation.example.class: Vision\PresentationBundle\Example

services:
#    vision_presentation.example:
#        class: %vision_presentation.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
